[2024-06-29T19:25:30.040+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T19:25:30.078+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: group_dag_v2.downloads scheduled__2024-06-28T00:00:00+00:00 [queued]>
[2024-06-29T19:25:30.089+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: group_dag_v2.downloads scheduled__2024-06-28T00:00:00+00:00 [queued]>
[2024-06-29T19:25:30.089+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-29T19:25:30.104+0700] {taskinstance.py:2330} INFO - Executing <Task(SubDagOperator): downloads> on 2024-06-28 00:00:00+00:00
[2024-06-29T19:25:30.112+0700] {standard_task_runner.py:63} INFO - Started process 111153 to run task
[2024-06-29T19:25:30.119+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'group_dag_v2', 'downloads', 'scheduled__2024-06-28T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/group_dag_v2.py', '--cfg-path', '/tmp/tmpt_sn0cwp']
[2024-06-29T19:25:30.123+0700] {standard_task_runner.py:91} INFO - Job 54: Subtask downloads
[2024-06-29T19:25:30.267+0700] {task_command.py:426} INFO - Running <TaskInstance: group_dag_v2.downloads scheduled__2024-06-28T00:00:00+00:00 [running]> on host daniel
[2024-06-29T19:25:30.463+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='group_dag_v2' AIRFLOW_CTX_TASK_ID='downloads' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-28T00:00:00+00:00'
[2024-06-29T19:25:30.472+0700] {logging_mixin.py:188} WARNING - /home/daniel/***/venv/lib/python3.10/site-packages/***/utils/context.py:212 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-06-29T19:25:30.526+0700] {subdag.py:180} INFO - Created DagRun: scheduled__2024-06-28T00:00:00+00:00
[2024-06-29T19:25:30.526+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T19:31:36.607+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T19:31:36.625+0700] {process_utils.py:132} INFO - Sending 15 to group 111153. PIDs of all processes in the group: [111153]
[2024-06-29T19:31:36.625+0700] {process_utils.py:87} INFO - Sending the signal 15 to group 111153
[2024-06-29T19:31:36.626+0700] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-29T19:31:36.626+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T19:31:36.646+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/sensors/base.py", line 292, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-29T19:31:36.769+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=group_dag_v2, task_id=downloads, run_id=scheduled__2024-06-28T00:00:00+00:00, execution_date=20240628T000000, start_date=20240629T122530, end_date=20240629T123136
[2024-06-29T19:31:36.847+0700] {process_utils.py:80} INFO - Process psutil.Process(pid=111153, status='terminated', exitcode=2, started='19:25:29') (111153) terminated with exit code 2
