[2024-06-24T11:50:52.462+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T11:50:52.480+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.create_table manual__2024-06-24T04:50:36.069124+00:00 [queued]>
[2024-06-24T11:50:52.488+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.create_table manual__2024-06-24T04:50:36.069124+00:00 [queued]>
[2024-06-24T11:50:52.488+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T11:50:52.497+0700] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2024-06-24 04:50:36.069124+00:00
[2024-06-24T11:50:52.503+0700] {standard_task_runner.py:63} INFO - Started process 30788 to run task
[2024-06-24T11:50:52.506+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2024-06-24T04:50:36.069124+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpjbo3skr5']
[2024-06-24T11:50:52.507+0700] {standard_task_runner.py:91} INFO - Job 11: Subtask create_table
[2024-06-24T11:50:52.563+0700] {task_command.py:426} INFO - Running <TaskInstance: user_processing.create_table manual__2024-06-24T04:50:36.069124+00:00 [running]> on host daniel
[2024-06-24T11:50:52.649+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T04:50:36.069124+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T04:50:36.069124+00:00'
[2024-06-24T11:50:52.650+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T11:50:52.650+0700] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        
[2024-06-24T11:50:52.662+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T11:50:52.675+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/daniel/airflow/venv/lib/python3.10/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2024-06-24T11:50:52.678+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=user_processing, task_id=create_table, run_id=manual__2024-06-24T04:50:36.069124+00:00, execution_date=20240624T045036, start_date=20240624T045052, end_date=20240624T045052
[2024-06-24T11:50:52.687+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task create_table (The conn_id `postgres` isn't defined; 30788)
[2024-06-24T11:50:52.722+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T11:50:52.742+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T11:50:52.743+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
